function plot_graph(time_serie,power_serie,xlim_fig,title_fig,xlab_name,ylab_name,avg_value)
    plot(time_serie(:), power_serie(:), 'o-', ...
        'Color', '#0077b6', ...
        'LineWidth', 2, ...
        'MarkerFaceColor', '#0077b6', ...
        'MarkerEdgeColor', '#0077b6', ...
        'DisplayName', 'Data');
    xlabel(xlab_name);
    ylabel(ylab_name);
    title(title_fig)
    set(gca, 'Position', [0.12,0.12,xlim_fig,0.80])
    
    label = sprintf('Avr %.2e', avg_value);

    if avg_value>0
        yline(avg_value, '--r', ...
            'LineWidth', 2, ...
            'Color', 'r', ...
            'DisplayName', label);
    end
    
    legend('show')

end